language: php
php:
  - 7.1


env:
  global:
    - setup=basic

git:
  depth: 1

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: setup=stable

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]] ; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi

before_script:
  - cp .env.travis .env
  - mysql -e 'create database testing;'


script: vendor/bin/phpunit